#!/bin/bash

if [[ ! -d out ]]; then
sudo rm -r out
fi
if [[ ! -d gcc ]]; then
git clone https://github.com/Ruben1863/android_gcc_4.9_arm-linux-androideabi gcc
fi
mkdir -p out
export KBUILD_BUILD_USER=RuB3N1863
export KBUILD_BUILD_HOST=X5_Pro
export CROSS_COMPILE=${PWD}/gcc/bin/arm-linux-androideabi-
export USE_CCACHE=1
export ARCH=arm
export SUBARCH=arm
export TARGET=out
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE x5_pro_defconfig | tee -a Defconfig.log
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc --all) | tee -a Kernel.log
